### PR TITLE
Close #38

### LINKED ISSUE #38: Add GitHub templates
Add the DNN community standard GitHub templates for issues and pull requests

### PR DESCRIPTION
**Pull request by EPTamminga**
Adding GitHub templates to the repo

### CODE REVIEW

**Review by valadas — COMMENTED** [review]
On this one, I would like the opinion of the TAG group, it may be a bit special case since it may be included in Evoq/Engage...

**Comment by EPTamminga** [comment]
@valadas: I know, but this is no code change  just improving the issue content and documentation.  I included a reviewer from corp as well.

**Comment by galatrash** [comment]
@EPTamminga , I'm no longer with the DNN development team. I added @zyhfish who is still with the team.

**Comment by david-poindexter** [comment]
@valadas this is still part of DNN Platform and is open-source. This PR is just helping with the submission of issues.

**Comment by valadas** [comment]
Well for me it looks good.

**Pull request merged**
