### PR TITLE
rtl support

### PR DESCRIPTION
**Pull request by farsica**
correct showing grid data in right to left mode
correct showing date in other culture other than en-us

### CODE REVIEW

**Comment by cathalconnolly** [comment]
Cheers - that part of the UI was cut and paste from somewhere else (host->superusers) so it's probable that code came with it. However as we were using DNN 6.2.0 as the base it's also probable this was fixed in a later release. I'll ensure this get's merged for the next release.

**Comment by farsica** [comment]
thanks cathal, there was a compilation error that I fixed it
there is another error: the source code reference to dnn 7.0.2 and .net version set to 3.5 therefore can not compile the solution, dnn 7 need ,net 4

**Comment by cathalconnolly** [comment]
the reference should be to DNN 6.2.0 as that's the minimum version we require - .net 3.5sp1 applications will work in .net 4.0/.net 4.5 without recompilation

**Comment by valadas** [comment]
Hi @farsica , I did a manual merge because there was a conflicting file and unrelated changes to the RTL support. Just FYI next time, it is best to create a subject branch in order to isolate changes for a specific PR.

**Pull request merged**
